# dispnetCSR with all 3x3 kernels + clean data
# python main.py --cuda --outf ./models/cleandata-models-dispCSR-ks --lr 0.001 --logFile cleandata-train-dispCSR-ks.log --showFreq 1 --devices 0,1,2,3 --trainlist ./lists/SHAOHUAI_CLEAN_FlyingThings3D_release_TRAIN.list --vallist ./lists/SHAOHUAI_CLEAN_FlyingThings3D_release_TEST.list --endEpoch 100
#python main.py --cuda --outf ./models/cleandata-models-dispCSR-ks --lr 2.5e-5 --logFile cleandata-train-dispCSR-ks-cont4.log --showFreq 1 --devices 0,1 --trainlist ./lists/SHAOHUAI_CLEAN_FlyingThings3D_release_TRAIN.list --vallist ./lists/SHAOHUAI_CLEAN_FlyingThings3D_release_TEST.list --model ./models/cleandata-models-dispCSR-ks/model_best.pth --endEpoch 30 --batchSize 4

# dispnetCSR best model + KITTI
# python main.py --cuda --outf ./models/kitti-models-dispCSR --lr 0.001 --logFile kitti-train-dispCSR.log --showFreq 1 --devices 0,1,2,3 --trainlist ./lists/KITTI_TRAIN.list --vallist ./lists/KITTI_TEST.list --endEpoch 100 --model ./models/cleandata-models-dispCSRes-exp/model_best.pth --endEpoch 100 --devices 0,1

# dispnetCSR best model + virtual-style
#python main.py --cuda --outf ./models/virtual-dispCSR --lr 0.0001 --logFile virtual-train-dispCSR.log --showFreq 1 --trainlist ./lists/girl-1024x1024_TRAIN.list --vallist ./lists/girl-1024x1024_TEST.list --model ./models/virtual-dispCSR/model_best.pth --endEpoch 300 --devices 0,1 --datapath /media/external/data/virtual2

# dispnetCSR best model + virtual2-1024 + real(unsupervised)
# python main.py --cuda --outf ./models/virtual-dispCSR --lr 0.0001 --logFile virtual-train-dispCSR.log --showFreq 1 --trainlist ./lists/girl-1024x1024_TRAIN.list --vallist ./lists/girl-1024x1024_TEST.list --tdlist ./lists/real_release.list --model ./models/virtual-dispCSR/model_best.pth --endEpoch 300 --devices 0,1 --datapath /media/external/data/virtual2 --domain_transfer 1 --unsuper_alpha 0.2

# dispnetCSR best model + virtual with unsupervised loss
#python main.py --cuda --outf ./models/real-dispCSR-in1024 --lr 1e-3 --logFile real-train-dispCSR-1024in-r1.log --showFreq 1 --trainlist ./lists/virtual01-1024x1024_TRAIN.list --vallist ./lists/virtual01-1024x1024_TEST.list --tdlist ./lists/real_release.list --startEpoch 0 --endEpoch 300 --devices 0 --datapath /media/external/data/virtual --domain_transfer 1 --flowDiv 1.0 --model models/cleandata-models-dispCSRes-exp/model_best.pth --batchSize 1
#python main.py --cuda --outf ./models/flying-real-dispCSR-in1024 --lr 1e-4 --logFile flying-real-train-dispCSR-1024in-r1.log --showFreq 1 --trainlist ./lists/SHAOHUAI_CLEAN_FlyingThings3D_release_TRAIN.list --vallist ./lists/SHAOHUAI_CLEAN_FlyingThings3D_release_TEST.list --tdlist ./lists/real_release.list --startEpoch 0 --endEpoch 300 --devices 0 --datapath /media/external/data --domain_transfer 1 --flowDiv 1.0 --model models/cleandata-models-dispCSRes-exp/model_best.pth --batchSize 2
python main.py --cuda --outf ./models/flying-real-dispCSRWithMono-in1024 --lr 1e-4 --logFile flying-real-train-dispCSRWithMono-1024in-r1.log --showFreq 1 --trainlist ./lists/SHAOHUAI_CLEAN_FlyingThings3D_release_TRAIN.list --vallist ./lists/SHAOHUAI_CLEAN_FlyingThings3D_release_TEST.list --tdlist ./lists/real_release.list --startEpoch 0 --endEpoch 300 --devices 0,1 --datapath /media/external/data --domain_transfer 1 --flowDiv 1.0 --model ./dispnetcsres-mono.pth --batchSize 4

# Shaohuai run KITTI 
#python main.py --cuda --outf ./models/kitti--models-dispCSRes --lr 0.00001 --logFile kitti-train-dispCSRes.log --showFreq 1 --devices 0,1,2,3 --trainlist ./lists/KITTI_TRAIN.list --vallist ./lists/KITTI_TEST.list --startEpoch 1 --model ./models/girl-models-dispCSRes-finetune-crop-2nd/model_best.pth --datapath /home/datasets/imagenet/dispnet --batchSize 8 --endEpoch 400
#python main.py --cuda --outf ./models/kitti--models-dispCSRes-2nd --lr 0.00001 --logFile kitti-train-dispCSRes-2nd.log --showFreq 1 --devices 0,1,2,3 --trainlist ./lists/KITTI_TRAIN.list --vallist ./lists/KITTI_TEST.list --startEpoch 1 --model ./models/kitti--models-dispCSRes/model_best.pth --datapath /home/datasets/imagenet/dispnet --batchSize 8 --endEpoch 800
# python main.py --cuda --outf ./models/kitti-models-dispCSR --lr 0.001 --logFile kitti-train-dispCSR.log --showFreq 1 --devices 0,1,2,3 --trainlist ./lists/KITTI_TRAIN.list --vallist ./lists/KITTI_TEST.list --model ./models/cleandata-models-dispCSRes-exp/model_best.pth --endEpoch 300 --devices 0,1

# python main.py --cuda --outf /data2/models/girl1024x1024 --lr 0.0001 --logFile girl1024.log --showFreq 1 --devices 0,1,2,3 --datapath /data2/virtual2 --trainlist ./lists/girl-1024x1024_TRAIN.list --vallist ./lists/girl-1024x1024_TEST.list --endEpoch 200 --batchSize 8
# python main.py --cuda --outf /data2/models/girl1024x1024 --lr 0.0001 --logFile girl1024.log --showFreq 1 --devices 0,1,2,3 --datapath /data2/virtual2 --trainlist ./lists/girl-1024x1024_TRAIN.list --vallist ./lists/girl-1024x1024_TEST.list --endEpoch 200 --batchSize 8 --model /data2/models/girl1024x1024/model_best.pth
